/**
 * Database Record Types
 *
 * Provides type-safe interfaces for database operations while supporting
 * dynamic user-defined schemas. All records include system fields, with
 * user fields being flexible.
 */

/**
 * System fields that are present on all database records
 * These are automatically managed by the platform
 */
export interface SystemFields {
    id: string;
    access_read: string[] | null;
    access_edit: string[] | null;
    access_full: string[] | null;
    access_deny: string[] | null;
    created_at: string;
    updated_at: string;
    trashed_at: string | null;
    deleted_at: string | null;
}

/**
 * Partial system fields for record creation
 * Only id and access fields can be optionally provided by user
 */
export interface PartialSystemFields {
    id?: string;
    access_read?: string[] | null;
    access_edit?: string[] | null;
    access_full?: string[] | null;
    access_deny?: string[] | null;
}

/**
 * Base record type combining system fields with dynamic user data
 * Generic parameter allows typing user-defined fields when schema is known
 *
 * @example
 * // For unknown schema
 * const record: DbRecord = await db.selectOne('users', filter);
 *
 * // For known schema
 * interface UserFields {
 *   email: string;
 *   name: string;
 * }
 * const user: DbRecord<UserFields> = await db.selectOne('users', filter);
 * console.log(user.email); // Type-safe!
 */
export type DbRecord<T extends Record<string, any> = Record<string, any>> = SystemFields & T;

/**
 * Input record type for creating new records
 * System fields are optional (except what user can provide)
 * Timestamps are auto-generated by database
 *
 * @example
 * const newUser: DbCreateInput<UserFields> = {
 *   email: 'test@example.com',
 *   name: 'Test User',
 *   access_read: ['user-123']  // Optional
 * };
 */
export type DbCreateInput<T extends Record<string, any> = Record<string, any>> = T & PartialSystemFields;

/**
 * Input record type for updating existing records
 * Must include id, all other fields are optional updates
 *
 * @example
 * const update: DbUpdateInput<UserFields> = {
 *   id: 'user-123',
 *   name: 'Updated Name'  // Partial updates allowed
 * };
 */
export type DbUpdateInput<T extends Record<string, any> = Record<string, any>> = {
    id: string;
} & Partial<T> & Partial<PartialSystemFields>;

/**
 * Input for delete operations
 * Only requires the record ID
 */
export interface DbDeleteInput {
    id: string;
}

/**
 * Access control update input
 * Only allows modification of access_* fields
 */
export interface DbAccessInput {
    access_read?: string[] | null;
    access_edit?: string[] | null;
    access_full?: string[] | null;
    access_deny?: string[] | null;
}

/**
 * Schema-specific record types for system schemas
 * These have known, fixed structures
 */

export interface SchemaRecord extends DbRecord {
    schema_name: string;
    status: string;
    sudo?: boolean;
    external?: boolean;
    definition?: any;
}

export interface ColumnRecord extends DbRecord {
    schema_name: string;
    column_name: string;
    type: string;
    required?: boolean;
    default_value?: any;
    description?: string;
    pattern?: string;
    minimum?: number;
    maximum?: number;
    min_length?: number;
    max_length?: number;
    enum_values?: string[];
    relationship_type?: 'owned' | 'referenced';
    relationship_schema?: string;
    relationship_name?: string;
    relationship_column?: string;
    relationship_cascade_delete?: boolean;
    relationship_required?: boolean;
}

export interface DefinitionRecord extends DbRecord {
    schema_name: string;
    definition: any;
}

export interface UserRecord extends DbRecord {
    username: string;
    email: string;
    password_hash?: string;
    status?: string;
    roles?: string[];
}

export interface SessionRecord extends DbRecord {
    user_id: string;
    token: string;
    expires_at: string;
    ip_address?: string;
    user_agent?: string;
}
