-- ============================================================================
-- DATA: Register extract schemas and define columns
-- ============================================================================

-- Register extracts schema
INSERT INTO "schemas" (schema_name, status, sudo, description)
VALUES (
    'extracts',
    'system',
    false,
    'Data extraction job configurations'
);

-- Register extract_runs schema
INSERT INTO "schemas" (schema_name, status, sudo, description)
VALUES (
    'extract_runs',
    'system',
    false,
    'Individual execution runs of extract jobs'
);

-- Register extract_artifacts schema
INSERT INTO "schemas" (schema_name, status, sudo, description)
VALUES (
    'extract_artifacts',
    'system',
    false,
    'Downloadable files generated by extract runs'
);

-- ============================================================================
-- COLUMNS FOR: extracts
-- ============================================================================
INSERT INTO "columns" (schema_name, column_name, type, required, description) VALUES
    ('extracts', 'name', 'text', true, 'Human-readable name for this extract'),
    ('extracts', 'description', 'text', false, 'Purpose and notes'),
    ('extracts', 'format', 'text', false, 'Output format: yaml, json, jsonl, archive'),
    ('extracts', 'include', 'text[]', false, 'What to include: describe, data, acls, files'),
    ('extracts', 'schemas', 'text[]', false, 'Specific schemas to extract (null = all)'),
    ('extracts', 'filter', 'jsonb', false, 'Optional filter to apply per schema'),
    ('extracts', 'compress', 'boolean', false, 'Gzip the output'),
    ('extracts', 'split_files', 'boolean', false, 'Create separate file per schema'),
    ('extracts', 'schedule', 'text', false, 'Cron expression'),
    ('extracts', 'schedule_enabled', 'boolean', false, 'Enable scheduled execution'),
    ('extracts', 'retention_days', 'integer', false, 'How long to keep artifacts'),
    ('extracts', 'enabled', 'boolean', false, 'Can this extract be executed'),
    ('extracts', 'last_run_id', 'uuid', false, 'Most recent execution'),
    ('extracts', 'last_run_status', 'text', false, 'Status of last run'),
    ('extracts', 'last_run_at', 'timestamp', false, 'When last executed'),
    ('extracts', 'total_runs', 'integer', false, 'Total execution count'),
    ('extracts', 'successful_runs', 'integer', false, 'Successful execution count'),
    ('extracts', 'failed_runs', 'integer', false, 'Failed execution count');

-- ============================================================================
-- COLUMNS FOR: extract_runs
-- ============================================================================
INSERT INTO "columns" (schema_name, column_name, type, required, description) VALUES
    ('extract_runs', 'extract_id', 'uuid', true, 'Foreign key to extracts table'),
    ('extract_runs', 'extract_name', 'text', false, 'Denormalized for easier queries'),
    ('extract_runs', 'status', 'text', true, 'Execution status: pending, queued, running, completed, failed, cancelled'),
    ('extract_runs', 'progress', 'integer', false, 'Completion percentage (0-100)'),
    ('extract_runs', 'progress_detail', 'jsonb', false, 'Detailed progress information'),
    ('extract_runs', 'started_at', 'timestamp', false, 'When execution began'),
    ('extract_runs', 'completed_at', 'timestamp', false, 'When execution finished'),
    ('extract_runs', 'duration_seconds', 'integer', false, 'Execution time in seconds'),
    ('extract_runs', 'records_exported', 'integer', false, 'Total records exported'),
    ('extract_runs', 'schemas_exported', 'integer', false, 'Number of schemas exported'),
    ('extract_runs', 'artifacts_created', 'integer', false, 'Number of artifacts generated'),
    ('extract_runs', 'total_size_bytes', 'bigint', false, 'Total size of all artifacts'),
    ('extract_runs', 'error', 'text', false, 'Error message if failed'),
    ('extract_runs', 'error_detail', 'jsonb', false, 'Detailed error context'),
    ('extract_runs', 'executed_by', 'uuid', false, 'User who triggered execution'),
    ('extract_runs', 'triggered_by', 'text', false, 'How it was triggered: manual, schedule, api'),
    ('extract_runs', 'config_snapshot', 'jsonb', false, 'Copy of extract config at execution time');

-- ============================================================================
-- COLUMNS FOR: extract_artifacts
-- ============================================================================
INSERT INTO "columns" (schema_name, column_name, type, required, description) VALUES
    ('extract_artifacts', 'run_id', 'uuid', true, 'Foreign key to extract_runs table'),
    ('extract_artifacts', 'extract_id', 'uuid', true, 'Denormalized for cleanup queries'),
    ('extract_artifacts', 'artifact_type', 'text', true, 'Type: describe, data-{schema}, manifest'),
    ('extract_artifacts', 'artifact_name', 'text', true, 'Filename'),
    ('extract_artifacts', 'storage_path', 'text', true, 'Local path or cloud key'),
    ('extract_artifacts', 'storage_backend', 'text', false, 'Storage backend: local, s3, gcs, azure'),
    ('extract_artifacts', 'download_url', 'text', false, 'Public or signed URL for download'),
    ('extract_artifacts', 'format', 'text', false, 'File format: jsonl, yaml, json, tar.gz'),
    ('extract_artifacts', 'size_bytes', 'bigint', true, 'File size in bytes'),
    ('extract_artifacts', 'checksum', 'text', false, 'SHA256 hash for integrity'),
    ('extract_artifacts', 'content_type', 'text', false, 'MIME type'),
    ('extract_artifacts', 'expires_at', 'timestamp', false, 'When this artifact will be deleted'),
    ('extract_artifacts', 'accessed_at', 'timestamp', false, 'Last download time'),
    ('extract_artifacts', 'download_count', 'integer', false, 'Number of downloads'),
    ('extract_artifacts', 'is_primary', 'boolean', false, 'Primary downloadable artifact');
