-- Compiled Fixture: system (SQLite)
-- Generated: 2025-11-25
--
-- SQLite version of system fixture
-- UUIDs are generated by the application, not the database

BEGIN;

-- ============================================================================
-- MODEL: models
-- ============================================================================
CREATE TABLE "models" (
    "id" TEXT PRIMARY KEY NOT NULL,
    "access_read" TEXT DEFAULT '[]',
    "access_edit" TEXT DEFAULT '[]',
    "access_full" TEXT DEFAULT '[]',
    "access_deny" TEXT DEFAULT '[]',
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "trashed_at" TEXT,
    "deleted_at" TEXT,
    "model_name" TEXT NOT NULL,
    "status" TEXT DEFAULT 'active' NOT NULL,
    "description" TEXT,
    "sudo" INTEGER DEFAULT 0 NOT NULL,
    "frozen" INTEGER DEFAULT 0 NOT NULL,
    "immutable" INTEGER DEFAULT 0 NOT NULL,
    "external" INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT "model_name_unique" UNIQUE("model_name")
);

-- ============================================================================
-- MODEL: fields
-- ============================================================================
CREATE TABLE "fields" (
    "id" TEXT PRIMARY KEY NOT NULL,
    "access_read" TEXT DEFAULT '[]',
    "access_edit" TEXT DEFAULT '[]',
    "access_full" TEXT DEFAULT '[]',
    "access_deny" TEXT DEFAULT '[]',
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "trashed_at" TEXT,
    "deleted_at" TEXT,
    "model_name" TEXT NOT NULL,
    "field_name" TEXT NOT NULL,
    "type" TEXT NOT NULL CHECK ("type" IN (
        'text', 'integer', 'bigint', 'bigserial', 'numeric', 'boolean',
        'jsonb', 'uuid', 'timestamp', 'date',
        'text[]', 'integer[]', 'numeric[]', 'uuid[]'
    )),
    "required" INTEGER DEFAULT 0 NOT NULL,
    "default_value" TEXT,
    "description" TEXT,
    "relationship_type" TEXT,
    "related_model" TEXT,
    "related_field" TEXT,
    "relationship_name" TEXT,
    "cascade_delete" INTEGER DEFAULT 0,
    "required_relationship" INTEGER DEFAULT 0,
    "minimum" REAL,
    "maximum" REAL,
    "pattern" TEXT,
    "enum_values" TEXT,
    "is_array" INTEGER DEFAULT 0,
    "immutable" INTEGER DEFAULT 0 NOT NULL,
    "sudo" INTEGER DEFAULT 0 NOT NULL,
    "unique" INTEGER DEFAULT 0 NOT NULL,
    "index" INTEGER DEFAULT 0 NOT NULL,
    "tracked" INTEGER DEFAULT 0 NOT NULL,
    "searchable" INTEGER DEFAULT 0 NOT NULL,
    "transform" TEXT,
    FOREIGN KEY ("model_name") REFERENCES "models"("model_name")
);

CREATE UNIQUE INDEX "idx_fields_model_field" ON "fields" ("model_name", "field_name");

-- ============================================================================
-- MODEL: users
-- ============================================================================
CREATE TABLE "users" (
    "id" TEXT PRIMARY KEY NOT NULL,
    "name" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "access" TEXT CHECK ("access" IN ('root', 'full', 'edit', 'read', 'deny')) NOT NULL,
    "access_read" TEXT DEFAULT '[]',
    "access_edit" TEXT DEFAULT '[]',
    "access_full" TEXT DEFAULT '[]',
    "access_deny" TEXT DEFAULT '[]',
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "trashed_at" TEXT,
    "deleted_at" TEXT,
    CONSTRAINT "users_auth_unique" UNIQUE("auth")
);

-- ============================================================================
-- DATA: Register models
-- ============================================================================
INSERT INTO "models" (id, model_name, status, sudo) VALUES
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'system', 1),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'system', 1),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'users', 'system', 1);

-- ============================================================================
-- DATA: Fields for models
-- ============================================================================
INSERT INTO "fields" (id, model_name, field_name, type, required, default_value, description) VALUES
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'model_name', 'text', 1, NULL, 'Unique name for the model'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'status', 'text', 0, 'active', 'Model status (active, disabled, system)'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'description', 'text', 0, NULL, 'Human-readable description of the model'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'sudo', 'boolean', 0, NULL, 'Whether model modifications require sudo access'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'frozen', 'boolean', 0, NULL, 'Whether all data changes are prevented on this model'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'immutable', 'boolean', 0, NULL, 'Whether records are write-once (can be created but never modified)'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'models', 'external', 'boolean', 0, NULL, 'Whether model is managed externally (skip DDL operations)');

-- ============================================================================
-- DATA: Fields for fields
-- ============================================================================
INSERT INTO "fields" (id, model_name, field_name, type, required, description) VALUES
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'model_name', 'text', 1, 'Name of the model this field belongs to'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'field_name', 'text', 1, 'Name of the field'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'type', 'text', 1, 'Data type of the field'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'required', 'boolean', 0, 'Whether the field is required (NOT NULL)'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'default_value', 'text', 0, 'Default value for the field'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'description', 'text', 0, 'Human-readable description of the field'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'relationship_type', 'text', 0, 'Type of relationship (owned, referenced)'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'related_model', 'text', 0, 'Related model for relationships'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'related_field', 'text', 0, 'Related field for relationships'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'relationship_name', 'text', 0, 'Name of the relationship'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'cascade_delete', 'boolean', 0, 'Whether to cascade delete on relationship'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'required_relationship', 'boolean', 0, 'Whether the relationship is required'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'minimum', 'numeric', 0, 'Minimum value constraint for numeric fields'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'maximum', 'numeric', 0, 'Maximum value constraint for numeric fields'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'pattern', 'text', 0, 'Regular expression pattern for validation'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'enum_values', 'text[]', 0, 'Allowed enum values'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'is_array', 'boolean', 0, 'Whether the field is an array type'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'immutable', 'boolean', 0, 'Whether the field value cannot be changed once set'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'sudo', 'boolean', 0, 'Whether modifying this field requires sudo access'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'unique', 'boolean', 0, 'Whether the field must have unique values'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'index', 'boolean', 0, 'Whether to create a standard btree index on this field'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'tracked', 'boolean', 0, 'Whether changes to this field are tracked in history'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'searchable', 'boolean', 0, 'Whether to enable full-text search with GIN index'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'fields', 'transform', 'text', 0, 'Auto-transform values: lowercase, uppercase, trim, normalize_phone, normalize_email');

-- ============================================================================
-- DATA: Fields for users
-- ============================================================================
INSERT INTO "fields" (id, model_name, field_name, type, required, description) VALUES
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'users', 'name', 'text', 1, 'User display name'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'users', 'auth', 'text', 1, 'Authentication identifier'),
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'users', 'access', 'text', 1, 'User access level (root, full, edit, read, deny)');

-- ============================================================================
-- DATA: Default root user
-- ============================================================================
INSERT OR IGNORE INTO "users" (id, name, auth, access) VALUES
    (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))), 'root', 'root', 'root');

COMMIT;
