-- ============================================================================
-- MODEL: extract_artifacts
-- ============================================================================
-- Individual downloadable files generated by extract runs

CREATE TABLE "extract_artifacts" (
    -- System fields
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"access_read" uuid[] DEFAULT '{}'::uuid[],
	"access_edit" uuid[] DEFAULT '{}'::uuid[],
	"access_full" uuid[] DEFAULT '{}'::uuid[],
	"access_deny" uuid[] DEFAULT '{}'::uuid[],
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"trashed_at" timestamp,
	"deleted_at" timestamp,

	-- Relationships
	"run_id" uuid NOT NULL,
	"extract_id" uuid NOT NULL,

	-- Artifact identity
	"artifact_type" text NOT NULL,
	"artifact_name" text NOT NULL,

	-- Storage
	"storage_path" text NOT NULL,
	"storage_backend" text DEFAULT 'local' CHECK ("storage_backend" IN ('local', 's3', 'gcs', 'azure')),
	"download_url" text,

	-- Metadata
	"format" text,
	"size_bytes" bigint NOT NULL,
	"checksum" text,
	"content_type" text DEFAULT 'application/octet-stream',

	-- Lifecycle
	"expires_at" timestamp,
	"accessed_at" timestamp,
	"download_count" integer DEFAULT 0,

	-- Flags
	"is_primary" boolean DEFAULT false
);

-- Foreign keys
ALTER TABLE "extract_artifacts" ADD CONSTRAINT "extract_artifacts_run_id_fk"
    FOREIGN KEY ("run_id") REFERENCES "extract_runs"("id")
    ON DELETE CASCADE;

-- Indexes
CREATE INDEX "idx_extract_artifacts_run_id" ON "extract_artifacts" ("run_id");
CREATE INDEX "idx_extract_artifacts_extract_id" ON "extract_artifacts" ("extract_id");
CREATE INDEX "idx_extract_artifacts_expires_at" ON "extract_artifacts" ("expires_at") WHERE "expires_at" IS NOT NULL;
